[window]
dynamic_title = true
opacity = 0.85
decorations = "None"

[env]
TERM = "xterm-256color"

[font]
size = 11.5

[font.bold]
family = "FiraMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraMono Nerd Font Monoe"
style = "Italic"

[font.normal]
family = "FiraMono Nerd Font Mono"
style = "Regular"
