import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-mocha.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-latte.toml"
]
[window]
dynamic_title = true
opacity = 0.95

[env]
TERM = "xterm-256color"

[font]

normal = { family = "JetBrainsMono Nerd Font", style = "<string>" }

size = 11.25

