import = [
    # uncomment the flavour you want below:
    #"~/.config/alacritty/catppuccin-mocha.toml"
    #"~/.config/alacritty/catppuccin-macchiato.toml"
    # "~/.config/alacritty/catppuccin-frappe.toml"
    # "~/.config/alacritty/catppuccin-latte.toml"
    #"~/.config/alacritty/rose-pine.toml"
    #"~/.config/alacritty/rose-pine-moon.toml"
]
[window]
dynamic_title = true

[env]
TERM = "xterm-256color"

[font]

#normal = { family = "Ubuntu", style = "Regular" }

size = 11

[font.normal]
family = "Ubuntu Nerd Font"

